### ISSUE TITLE
Add an AZ field to the Spec

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/awstpr#11]
If no AZ field is specified, EC2 instances are assigned one automatically by AWS.

We want to control the AZ, so that the LB and the instances end up in the same one and can actually see each other.

An alternative is to rename the "region" field to "az", but I think that's a worse solution, as we would have to strip the last character from the AZ to get a Region in some contexts.

**Comment by xh3b4sd** [comment]
Based on http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html I would say we have both. Region to specify the geographic area and AZ to specify the zone inside the region. Does that make sense? I would then just use a decent default as it makes sense, whatever that then means.
